services:
  mongodb:
    image: vijayamudalapalli/mongodb:v1
    container_name: mongodb
  catalogue:
    image: vijayamudalapalli/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: vijayamudalapalli/redis:v1
    container_name: redis
  mysql:
    image: vijayamudalapalli/mysql:v1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Roboshop@1"
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  user:
    image: vijayamudalapalli/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    image: vijayamudalapalli/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  shipping:
    image: vijayamudalapalli/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
  payment:
    image: vijayamudalapalli/payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
      - cart
      - user
  frontend:
    image: vijayamudalapalli/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
    - user
    - catalogue
    - cart
    - shipping
    - payment
networks:
  default:
    driver: bridge
    name: roboshop
    external: false # true if you have created network manually using "docker network create roboshop" command